using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BSP.PowerHouse.DynamicsGP.Integration.Domain
{
    public partial class SOP10200_DTO
    {
        public short SOPTYPE { get; set; }
        public string SOPNUMBE { get; set; }
        public int LNITMSEQ { get; set; }
        public int CMPNTSEQ { get; set; }
        public string ITEMNMBR { get; set; }
        public string ITEMDESC { get; set; }
        public short NONINVEN { get; set; }
        public short DROPSHIP { get; set; }
        public string UOFM { get; set; }
        public string LOCNCODE { get; set; }
        public decimal UNITCOST { get; set; }
        public decimal ORUNTCST { get; set; }
        public decimal UNITPRCE { get; set; }
        public decimal ORUNTPRC { get; set; }
        public decimal XTNDPRCE { get; set; }
        public decimal OXTNDPRC { get; set; }
        public decimal REMPRICE { get; set; }
        public decimal OREPRICE { get; set; }
        public decimal EXTDCOST { get; set; }
        public decimal OREXTCST { get; set; }
        public decimal MRKDNAMT { get; set; }
        public decimal ORMRKDAM { get; set; }
        public short MRKDNPCT { get; set; }
        public short MRKDNTYP { get; set; }
        public int INVINDX { get; set; }
        public int CSLSINDX { get; set; }
        public int SLSINDX { get; set; }
        public int MKDNINDX { get; set; }
        public int RTNSINDX { get; set; }
        public int INUSINDX { get; set; }
        public int INSRINDX { get; set; }
        public int DMGDINDX { get; set; }
        public string ITMTSHID { get; set; }
        public short IVITMTXB { get; set; }
        public decimal BKTSLSAM { get; set; }
        public decimal ORBKTSLS { get; set; }
        public decimal TAXAMNT { get; set; }
        public decimal ORTAXAMT { get; set; }
        public decimal TXBTXAMT { get; set; }
        public decimal OTAXTAMT { get; set; }
        public byte BSIVCTTL { get; set; }
        public decimal TRDISAMT { get; set; }
        public decimal ORTDISAM { get; set; }
        public decimal DISCSALE { get; set; }
        public decimal ORDAVSLS { get; set; }
        public decimal QUANTITY { get; set; }
        public decimal ATYALLOC { get; set; }
        public decimal QTYINSVC { get; set; }
        public decimal QTYINUSE { get; set; }
        public decimal QTYDMGED { get; set; }
        public decimal QTYRTRND { get; set; }
        public decimal QTYONHND { get; set; }
        public decimal QTYCANCE { get; set; }
        public decimal QTYCANOT { get; set; }
        public decimal QTYONPO { get; set; }
        public decimal QTYORDER { get; set; }
        public decimal QTYPRBAC { get; set; }
        public decimal QTYPRBOO { get; set; }
        public decimal QTYPRINV { get; set; }
        public decimal QTYPRORD { get; set; }
        public decimal QTYPRVRECVD { get; set; }
        public decimal QTYRECVD { get; set; }
        public decimal QTYREMAI { get; set; }
        public decimal QTYREMBO { get; set; }
        public decimal QTYTBAOR { get; set; }
        public decimal QTYTOINV { get; set; }
        public decimal QTYTORDR { get; set; }
        public decimal QTYFULFI { get; set; }
        public decimal QTYSLCTD { get; set; }
        public decimal QTYBSUOM { get; set; }
        public decimal EXTQTYAL { get; set; }
        public decimal EXTQTYSEL { get; set; }
        public DateTime ReqShipDate { get; set; }
        public DateTime FUFILDAT { get; set; }
        public DateTime ACTLSHIP { get; set; }
        public string SHIPMTHD { get; set; }
        public string SALSTERR { get; set; }
        public string SLPRSNID { get; set; }
        public string PRCLEVEL { get; set; }
        public string COMMNTID { get; set; }
        public short BRKFLD1 { get; set; }
        public short BRKFLD2 { get; set; }
        public short BRKFLD3 { get; set; }
        public short CURRNIDX { get; set; }
        public string TRXSORCE { get; set; }
        public byte[] SOPLNERR { get; set; }
        public int ORGSEQNM { get; set; }
        public string ITEMCODE { get; set; }
        public short PURCHSTAT { get; set; }
        public short DECPLQTY { get; set; }
        public short DECPLCUR { get; set; }
        public short ODECPLCU { get; set; }
        public decimal QTYTOSHP { get; set; }
        public byte XFRSHDOC { get; set; }
        public byte EXCEPTIONALDEMAND { get; set; }
        public string TAXSCHID { get; set; }
        public short TXSCHSRC { get; set; }
        public string PRSTADCD { get; set; }
        public string ShipToName { get; set; }
        public string CNTCPRSN { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string CCode { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAXNUMBR { get; set; }
        public short Flags { get; set; }
        public decimal BackoutTradeDisc { get; set; }
        public decimal OrigBackoutTradeDisc { get; set; }
        public string GPSFOINTEGRATIONID { get; set; }
        public short INTEGRATIONSOURCE { get; set; }
        public string INTEGRATIONID { get; set; }
        public string CONTNBR { get; set; }
        public decimal CONTLNSEQNBR { get; set; }
        public DateTime CONTSTARTDTE { get; set; }
        public DateTime CONTENDDTE { get; set; }
        public string CONTITEMNBR { get; set; }
        public string CONTSERIALNBR { get; set; }
        public byte BULKPICKPRNT { get; set; }
        public byte INDPICKPRNT { get; set; }
        public byte ISLINEINTRA { get; set; }
        public string SOFULFILLMENTBIN { get; set; }
        public byte MULTIPLEBINS { get; set; }
        public short Print_Phone_NumberGB { get; set; }
    }
}
